-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.backtest_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  backtest_run_id text NOT NULL,
  snapshot_date date NOT NULL,
  set_name text NOT NULL,
  player text NOT NULL,
  variant text NOT NULL,
  estimated_price numeric,
  actual_price numeric,
  error_pct numeric,
  confidence text,
  method text,
  engine_version text,
  evidence_weight numeric,
  n_ref_points integer,
  ref_sets text,
  extrapolated boolean DEFAULT false,
  extrap_dir text,
  is_refreshed boolean DEFAULT false,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT backtest_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.engine_calibration_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  triggered_at timestamp with time zone DEFAULT now(),
  old_version integer NOT NULL,
  new_version integer NOT NULL,
  parameter_changed text NOT NULL,
  old_value numeric,
  new_value numeric,
  mae_before numeric,
  mae_after numeric,
  improvement_pct numeric,
  observations_used integer,
  reasoning text,
  was_applied boolean DEFAULT true,
  triggered_by text DEFAULT 'manual'::text,
  CONSTRAINT engine_calibration_log_pkey PRIMARY KEY (id),
  CONSTRAINT eng_cal_log_old_fkey FOREIGN KEY (old_version) REFERENCES public.engine_params(version),
  CONSTRAINT eng_cal_log_new_fkey FOREIGN KEY (new_version) REFERENCES public.engine_params(version)
);
CREATE TABLE public.engine_params (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  version integer NOT NULL UNIQUE,
  tag text,
  is_active boolean NOT NULL DEFAULT false,
  notes text,
  applied_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  staleness_tau numeric NOT NULL DEFAULT 90,
  evidence_k numeric NOT NULL DEFAULT 0.0231,
  weight_30d numeric NOT NULL DEFAULT 3.0,
  weight_90d numeric NOT NULL DEFAULT 1.5,
  weight_alltime numeric NOT NULL DEFAULT 1.0,
  recency_conf_30d numeric NOT NULL DEFAULT 1.0,
  recency_conf_90d numeric NOT NULL DEFAULT 0.7,
  recency_conf_alltime numeric NOT NULL DEFAULT 0.4,
  rarity_premium numeric NOT NULL DEFAULT 1.20,
  pop_proximity_floor numeric NOT NULL DEFAULT 0.60,
  league_same_weight numeric NOT NULL DEFAULT 0.90,
  league_diff_weight numeric NOT NULL DEFAULT 0.70,
  evidence_threshold numeric NOT NULL DEFAULT 0.15,
  quality_medium numeric NOT NULL DEFAULT 0.85,
  quality_medium_low numeric NOT NULL DEFAULT 0.65,
  quality_low numeric NOT NULL DEFAULT 0.40,
  quality_very_low numeric NOT NULL DEFAULT 0.20,
  extrap_cap_low numeric NOT NULL DEFAULT 0.10,
  extrap_cap_high numeric NOT NULL DEFAULT 10.0,
  mae_all_time numeric,
  mae_30d numeric,
  mae_by_confidence jsonb,
  mae_by_method jsonb,
  total_snapshots integer DEFAULT 0,
  resolved_snapshots integer DEFAULT 0,
  listing_blend numeric,
  listing_floor_discount numeric,
  supply_pressure numeric,
  afa_grade_multiplier numeric DEFAULT 2.0,
  mae_by_variant jsonb,
  CONSTRAINT engine_params_pkey PRIMARY KEY (id)
);
CREATE TABLE public.estimate_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_at timestamp with time zone NOT NULL DEFAULT now(),
  snapshot_run_id uuid NOT NULL,
  set_name text NOT NULL,
  player text NOT NULL,
  variant text NOT NULL,
  estimated_price numeric NOT NULL,
  confidence text,
  method text,
  engine_version integer NOT NULL,
  evidence_weight numeric,
  n_ref_points integer,
  ref_sets ARRAY,
  extrapolated boolean DEFAULT false,
  extrap_dir text,
  freshness numeric,
  is_refreshed boolean DEFAULT false,
  actual_price numeric,
  actual_date date,
  error_pct numeric,
  resolved_at timestamp with time zone,
  actual_afa_graded boolean DEFAULT false,
  CONSTRAINT estimate_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT estimate_snapshots_engine_fkey FOREIGN KEY (engine_version) REFERENCES public.engine_params(version)
);
CREATE TABLE public.ghostwrite_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  set_math_id uuid,
  buy_date date,
  channel text,
  buy_price numeric,
  year integer,
  player text,
  brand text,
  set_label text,
  size integer,
  var_raw text,
  variant text,
  population integer,
  cnt integer DEFAULT 1,
  note text,
  grade_date date,
  gr_fee numeric,
  total_cost numeric,
  graded text,
  grade numeric,
  inventory_name text,
  sell_date date,
  sell_channel text,
  sell_price numeric,
  pl numeric,
  match_status text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ghostwrite_inventory_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gl50_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  set_id uuid,
  set_name text NOT NULL,
  player text NOT NULL,
  variant text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  included_since date NOT NULL DEFAULT CURRENT_DATE,
  sort_order integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gl50_components_pkey PRIMARY KEY (id),
  CONSTRAINT gl50_components_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.sets(id)
);
CREATE TABLE public.listings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id text NOT NULL UNIQUE,
  legacy_item_id text,
  scraped_at timestamp with time zone NOT NULL,
  title text,
  ask_price numeric,
  currency text DEFAULT 'USD'::text,
  listing_type text,
  has_best_offer boolean DEFAULT false,
  bid_count integer,
  condition text,
  listed_date date,
  days_listed integer,
  image_url text,
  ebay_url text,
  seller text,
  seller_score integer,
  player text,
  variant text,
  set_name text,
  afa_grade text,
  ambiguous text,
  listing_status text,
  set_math_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT listings_pkey PRIMARY KEY (id),
  CONSTRAINT listings_set_math_id_fkey FOREIGN KEY (set_math_id) REFERENCES public.set_math(id)
);
CREATE TABLE public.players (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  league text,
  prior_tier smallint CHECK (prior_tier >= 1 AND prior_tier <= 3),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT players_pkey PRIMARY KEY (id)
);
CREATE TABLE public.price_signals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  set_name text NOT NULL,
  player text NOT NULL,
  variant text NOT NULL,
  avg_30d numeric,
  sales_30d integer DEFAULT 0,
  avg_90d numeric,
  sales_90d integer DEFAULT 0,
  avg_alltime numeric,
  sales_alltime integer DEFAULT 0,
  last_sale_price numeric,
  last_sale_date date,
  lowest_ask numeric,
  median_ask numeric,
  supply_count integer DEFAULT 0,
  implied_price numeric,
  implied_confidence text,
  avg_seller_reliability numeric,
  momentum numeric,
  is_stale boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT price_signals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  set_id uuid,
  player text,
  variant text,
  title text,
  price numeric,
  date date,
  image_url text,
  ebay_url text,
  afa_grade text,
  source text DEFAULT 'eBay'::text,
  status text,
  notes text,
  flagged boolean DEFAULT false,
  sheets_row_index integer UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  is_multi_sale boolean DEFAULT false,
  multi_sale_id integer,
  set_math_id uuid,
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.sets(id),
  CONSTRAINT sales_set_math_id_fkey FOREIGN KEY (set_math_id) REFERENCES public.set_math(id)
);
CREATE TABLE public.set_math (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  set_id uuid NOT NULL,
  player text NOT NULL,
  variant text NOT NULL,
  population integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  real_population integer,
  player_id uuid,
  CONSTRAINT set_math_pkey PRIMARY KEY (id),
  CONSTRAINT set_math_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.sets(id),
  CONSTRAINT set_math_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  league text,
  year integer,
  case_price numeric,
  figures_per_case integer,
  hit_ratio numeric DEFAULT 1.02,
  retail_price numeric,
  keywords ARRAY,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  image_url text,
  CONSTRAINT sets_pkey PRIMARY KEY (id)
);